### ISSUE TITLE
onPacketSending(PacketEvent) error

### ISSUE THREAD

**Issue by AfkF24** [tritonmc/Triton#102]
A onPacketSending(PacketEvent) error pops up in console whenever a player dies (from what I've noticed).

```
[13:42:59 ERROR]: [Triton] Unhandled exception occured in onPacketSending(PacketEvent) for Triton
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_201]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_201]
        at java.util.AbstractSet.removeAll(AbstractSet.java:177) ~[?:1.8.0_201]
        at com.rexcantor64.triton.h.d.a(ProtocolLibListener.java:991) ~[?:?]
        at com.rexcantor64.triton.h.d.onPacketSending(ProtocolLibListener.java:16327) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.15.2.jar:git-Paper-214]
        at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.15.2.jar:git-Paper-214]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1547) ~[?:git-Paper-214]
        at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1520) ~[?:git-Paper-214]
        at net.minecraft.server.v1_15_R1.EntityPlayer.tick(EntityPlayer.java:414) ~[patched_1.15.2.jar:git-Paper-214]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:794) ~[patched_1.15.2.jar:git-Paper-214]
        at net.minecraft.server.v1_15_R1.World.a(World.java:863) ~[patched_1.15.2.jar:git-Paper-214]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:516) ~[patched_1.15.2.jar:git-Paper-214]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.15.2.jar:git-Paper-214]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-214]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1151) ~[patched_1.15.2.jar:git-Paper-214]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-214]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[13:42:59 ERROR]: Parameters: 
  net.minecraft.server.v1_15_R1.PacketPlayOutEntityDestroy@427970ec[
    a={771599,739296,771222,767772,760273,759447,733690,771273,771269,733695,733694,742535,759685,767200,733691,771380,733698,768788,757267,758285,771600,763587,733697,742534,749902,733696,741208,759572,766750,733689,771257,767516,771601,733692,771379,749901,733688,759684,767837,759446,771602,764583,767201,733699,738614,768789,733693,759683,733700,737780,767202}
  ]
```

**Comment by diogotcorreia** [comment]
Can you please verify if this is still happening in v3.0.0?

**Comment by diogotcorreia** [comment]
Closed due to inactivity. Please open a new issue if the problem persists.
