### ISSUE TITLE
NullPointerException for Signs with null lines

### ISSUE THREAD

**Issue by diogotcorreia** [tritonmc/Triton#108]
**Describe the bug**
When a sign has a line set to `null`, Triton spams errors to the console.

**To Reproduce**
Not really sure how to reproduce. These signs seem to be created by plugins

**Expected behavior**
Triton should silently ignore the null lines.

**Server information (please complete the following information):**
 - Server Minecraft Version: `Tuinity 1.15.2`
 - Client Minecraft Version (if using ViaVersion or something similar): `unknown`
 - BungeeCord (specify if it's a fork) `unknown`
 - Triton Version: `2.6.4`

**Additional context**
Log:
```java
[13:00:12] [Server thread/ERROR]: [Triton] Unhandled exception occured in onPacketSending(PacketEvent) for Triton
java.lang.NullPointerException: null
	at com.rexcantor64.triton.m.a.a(ComponentUtils.java:89) ~[?:?]
	at com.rexcantor64.triton.f.b.a.a(AdvancedComponent.java:26) ~[?:?]
	at com.rexcantor64.triton.f.b.a.a(AdvancedComponent.java:17) ~[?:?]
	at com.rexcantor64.triton.h.d.g(ProtocolLibListener.java:548) ~[?:?]
	at com.rexcantor64.triton.h.d.onPacketSending(ProtocolLibListener.java:695) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_15_R1.NetworkManager.writePacket(NetworkManager.java:329) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:253) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1599) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1572) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.EntityPlayer.a(EntityPlayer.java:1820) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:2169) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:2103) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.Chunk.lambda$onNeighbourChange$1(Chunk.java:287) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1262) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1276) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:794) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1155) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1131) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Tuinity-"1aa9097"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[13:00:12] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_15_R1.PacketPlayOutMapChunk@7bcd2bc9[
    a=65
    b=15
    c=26623
    d={MOTION_BLOCKING:[*snip*]}
    e=net.minecraft.server.v1_15_R1.BiomeStorage@6e0767eb
    f={*snip*}
    g=[{Color:"black",Text4:'{"text":"na googlach"}',z:244,id:"minecraft:sign",y:141,x:1052,Text3:'{"text":"-sprawdz"}',Text2:'{"text":"w fonthill)"}',Text1:'{"text":"(taka jak"}'}, {Color:"black",Text4:"null",z:243,id:"minecraft:sign",y:141,x:1052,Text3:'{"text":"fajny hol"}',Text2:'{"text":"jakis "}',Text1:'{"text":"w srodku"}'}, {Color:"black",Text4:"null",z:243,id:"minecraft:sign",y:142,x:1052,Text3:'{"text":"wejscie"}',Text2:'{"text":"wyjebane "}',Text1:'{"text":"Jakies "}'}, {Color:"black",Text4:"null",z:242,id:"minecraft:sign",y:141,x:1052,Text3:"null",Text2:'{"text":"poziom"}',Text1:'{"text":"Najnizszy"}'}, {Color:"black",Text4:'{"text":"katedr"}',z:248,id:"minecraft:sign",y:141,x:1052,Text3:'{"text":"gotyckich"}',Text2:'{"text":"na podstawie"}',Text1:'{"text":"sciany"}'}, {Color:"black",Text4:'{"text":"glowstone)"}',z:247,id:"minecraft:sign",y:141,x:1052,Text3:'{"text":"(zanzaczone "}',Text2:'{"text":"z duzym oknem"}',Text1:'{"text":"Srodek"}'}, {Color:"black",Text4:"null",z:252,id:"minecraft:sign",y:141,x:1052,Text3:"null",Text2:'{"text":"najwyzsza wieza"}',Text1:'{"text":"w centurm"}'}, {Color:"black",Text4:"null",z:251,id:"minecraft:sign",y:141,x:1052,Text3:"null",Text2:"null",Text1:'{"text":"Najwyszy poziom"}'}, {Color:"black",Text4:"null",z:249,id:"minecraft:sign",y:141,x:1052,Text3:"null",Text2:'{"text":"i wgl"}',Text1:'{"text":"wysokie okna "}'}, {Color:"black",Text4:"null",z:253,id:"minecraft:sign",y:141,x:1052,Text3:'{"text":"okna po bokach"}',Text2:'{"text":"strzeliste "}',Text1:'{"text":"+ ladne"}'}]
    h=true
    ready=true
    extraPackets=[]
    mustSplit=false
  ]
```

**Comment by diogotcorreia** [comment]
Fixed on v3.0.3
