### ISSUE TITLE
Language GUI Selector Will Break if the Flag Has Grey 

### ISSUE THREAD

**Issue by Xuwznln** [tritonmc/Triton#112]
**Describe the bug**
As the title shows.

Example Color Code: eaiHhifEownFpL

Error Logs from Console:
`[17:49:41] [Server thread/INFO]: Xu_wznln issued server command: /triton
[17:49:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'triton' in plugin Triton v3.0.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[TTCW.jar:git-Paper-103]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[TTCW.jar:git-Paper-103]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[?:git-Paper-103]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[?:git-Paper-103]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[TTCW.jar:git-Paper-103]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[TTCW.jar:git-Paper-103]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.DyeColor.SILVER
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.DyeColor.valueOf(DyeColor.java:11) ~[TTCW.jar:git-Paper-103]
	at com.rexcantor64.triton.wrappers.items.ItemStackParser.bannerToItemStack(ItemStackParser.java:20) ~[?:?]
	at com.rexcantor64.triton.b.openLanguagesSelectionGUI(SpigotMLP.java:116) ~[?:?]
	at com.rexcantor64.triton.c.d.a(OpenSelectorCommand.java:26) ~[?:?]
	at com.rexcantor64.triton.c.a.f.a(CommandHandler.java:41) ~[?:?]
	at com.rexcantor64.triton.c.a.i.onCommand(SpigotCommandHandler.java:18) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[TTCW.jar:git-Paper-103]
	... 18 more`

**Server information (please complete the following information):**
 - Server Minecraft Version: paper 1.16.1
 - Client Minecraft Version: 1.16.1
 - BungeeCord yes
 - Triton Version: 3.0.2

**Comment by diogotcorreia** [comment]
Fixed.

Will be available on 3.0.3.
