### ISSUE TITLE
Sign's not working

### ISSUE THREAD

**Issue by Delanothje** [tritonmc/Triton#129]
**Describe the bug**
I try to setup a sign. But it sign stays empty

**To Reproduce**
I used the Triton sign set command

**Screenshots**
My configuration https://gyazo.com/77694cec41ec8f34cd464684b20cd6de
Empty sign https://gyazo.com/da3f0e18c4c3e0c8465c08f146fdd212

**Server information (please complete the following information):**
 - Server Minecraft Version: paper 1.12.2
 - Client Minecraft Version: 1.12.2
 - BungeeCord: Yes Waterfall
 - Triton Version: 3.1.8 

**Additional context**
I found this error in the lastesst.log
[14:28:39] [Server thread/WARN]: [Triton] Task #7132 for Triton v3.1.8 generated an exception
java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_272]
    at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_272]
    at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_272]
    at com.rexcantor64.triton.i.e.b(ProtocolLibListener.java:733) ~[?:?]
    at com.rexcantor64.triton.k.d.refreshAll(SpigotLanguagePlayer.java:2118) ~[?:?]
    at com.rexcantor64.triton.k.d$$Lambda$1513/0x000000003403df90.run(Unknown Source) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_272]

**Comment by Delanothje** [comment]
Sorry a mistake from me.
