### ISSUE TITLE
Triton errors on Bungeecord server

### ISSUE THREAD

**Issue by piotrskibapl** [tritonmc/Triton#159]
**Describe the bug**
The logs of my Bungeecord server contain a lot of error stacktraces coming from Triton. This error appear multiple times per second.

**To Reproduce**
Instal Triton on a Bungeecord server

**Expected behavior**
No errors should be present

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.16.5
 - Client Minecraft Version (if using ViaVersion or something similar): 1.16.5
 - BungeeCord (specify if it's a fork) [yes or no] yes
 - Triton Version: 3.6.0

**Additional context**
Console output:
```
21:01:21 [SEVERE] java.lang.NoClassDefFoundError: net/md_5/bungee/protocol/packet/Subtitle
21:01:21 [SEVERE] 	at com.rexcantor64.triton.packetinterceptor.BungeeListener.encode(BungeeListener.java:142)
21:01:21 [SEVERE] 	at com.rexcantor64.triton.packetinterceptor.BungeeListener.encode(BungeeListener.java:19)
21:01:21 [SEVERE] 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
21:01:21 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299)
21:01:21 [SEVERE] 	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
21:01:21 [SEVERE] 	at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:145)
21:01:21 [SEVERE] 	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:600)
21:01:21 [SEVERE] 	at net.md_5.bungee.protocol.packet.TabCompleteResponse.handle(TabCompleteResponse.java:98)
21:01:21 [SEVERE] 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
21:01:21 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
21:01:21 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
21:01:21 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
21:01:21 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
21:01:21 [SEVERE] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
21:01:21 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
21:01:21 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
21:01:21 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
21:01:21 [SEVERE] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
21:01:21 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
21:01:21 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
21:01:21 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
21:01:21 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
21:01:21 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
21:01:21 [SEVERE] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
21:01:21 [SEVERE] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by diogotcorreia** [comment]
You're not using the latest BungeeCord version. This can be solved by upgrading BungeeCord to the latest version, as one should always do since it's a proxy.
Either downgrade Triton to 3.5.3 or before, or upgrade BungeeCord.
