### ISSUE TITLE
Triton 3.7.0 isn't loading properly on Paper 1.16.5

### ISSUE THREAD

**Issue by piotrskibapl** [tritonmc/Triton#169]
**Describe the bug**
The plugin isn't loading properly on Paper 1.16.5 - an error in console is present.

**To Reproduce**
1. Setup a server with Paper 1.16.5, Triton 3.7.0 and ProtocolLib 4.7.0 (latest at the moment)
2. Try to run the server

**Expected behavior**
The plugin gets loaded correctly

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.16.5 (git-Paper-794)
 - Client Minecraft Version (if using ViaVersion or something similar): N/A
 - BungeeCord (specify if it's a fork): no
 - Triton Version: 3.7.0

**Additional context**
Console logs:
```
[04:01:41] [Server thread/INFO]: [Triton] Enabling Triton v3.7.0
[04:01:41] [Server thread/ERROR]: Error occurred while enabling Triton v3.7.0 (Is it up to date?)
java.lang.RuntimeException: Failed to find NMS class: advancements.Advancement$SerializedAdvancement
	at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$1(MinecraftReflection.java:2063) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_121]
	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2063) ~[?:?]
	at com.rexcantor64.triton.packetinterceptor.protocollib.AdvancementsPacketHandler.<init>(AdvancementsPacketHandler.java:34) ~[?:?]
	at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.<init>(ProtocolLibListener.java:90) ~[?:?]
	at com.rexcantor64.triton.SpigotMLP.onEnable(SpigotMLP.java:92) ~[?:?]
	at com.rexcantor64.triton.plugin.SpigotPlugin.onEnable(SpigotPlugin.java:18) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
Tested on a clean server install as well, same results observed.

**Comment by diogotcorreia** [comment]
I've already noticed this issue and I'm beginning to fix it.
Only MC versions 1.16 and below are affected.

Downgrading to Triton 3.6.x would fix the issue temporarily.

A fix for this on 3.7.1 will be released today.
