### ISSUE TITLE
NoSuchMethodError while translating items on older MC versions

### ISSUE THREAD

**Issue by diogotcorreia** [tritonmc/Triton#171]
Older versions of Spigot/Paper do not support the new `ComponentSerializer.toString(Object)` method from md5's chat library.

```java
java.lang.NoSuchMethodError: net.md_5.bungee.chat.ComponentSerializer.toString(Ljava/lang/Object;)Ljava/lang/String;
        at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.translateNbtItem(ProtocolLibListener.java:1312) ~[Triton.jar:?]
        at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.translateItemStack(ProtocolLibListener.java:1244) ~[Triton.jar:?]
        at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.handleSetSlot(ProtocolLibListener.java:595) ~[Triton.jar:?]
        at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.onPacketSending(ProtocolLibListener.java:790) ~[Triton.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:640) [ProtocolLib.jar:4.8.0-SNAPSHOT-b540]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596) [ProtocolLib.jar:4.8.0-SNAPSHOT-b540]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48) [ProtocolLib.jar:4.8.0-SNAPSHOT-b540]
        at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) [ProtocolLib.jar:4.8.0-SNAPSHOT-b540]
        at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) [ProtocolLib.jar:4.8.0-SNAPSHOT-b540]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_332]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_332]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
```

**Comment by diogotcorreia** [comment]
Fixed on a2287a72d6db8519119d1b58f9d82c1b1c2e62dc
