### ISSUE TITLE
Error EntityType

### ISSUE THREAD

**Issue by NecroSeigen** [tritonmc/Triton#179]
**Describe the bug**
It's not a bug that affect the game, so it doesn't look like one, it's just an error in the console when I join ad do certains actions, I can't describe in detail, the error appears randomly. See below. 

**Server information (please complete the following information):**
 - git-Purpur (build 1591 1.18.2)
 - BungeeCord No
 - Triton Version: 3.7.1

**Additional context**
```
[19:24:32 ERROR]: [Triton] Failed to get the EntityType from the type id. Is the plugin up to date?
[19:24:32 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 95 out of bounds for length 88
[19:24:32 WARN]:        at Triton-v3.7.1.jar//com.rexcantor64.triton.utils.EntityTypeUtils.getEntityTypeByIdNoCache(EntityTypeUtils.java:27)
[19:24:32 WARN]:        at Triton-v3.7.1.jar//com.rexcantor64.triton.utils.EntityTypeUtils.getEntityTypeById(EntityTypeUtils.java:16)
[19:24:32 WARN]:        at Triton-v3.7.1.jar//com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.handleSpawnEntityLiving(ProtocolLibListener.java:348)
[19:24:32 WARN]:        at Triton-v3.7.1.jar//com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.onPacketSending(ProtocolLibListener.java:792)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[19:24:32 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[19:24:32 WARN]:        at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:435)
[19:24:32 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:382)
[19:24:32 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2113)
[19:24:32 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[19:24:32 WARN]:        at net.minecraft.server.level.EntityTrackerEntry.sendPairingData(EntityTrackerEntry.java:285)
[19:24:32 WARN]:        at net.minecraft.server.level.EntityTrackerEntry.b(EntityTrackerEntry.java:270)
[19:24:32 WARN]:        at net.minecraft.server.level.PlayerChunkMap$EntityTracker.b(PlayerChunkMap.java:2345)
[19:24:32 WARN]:        at net.minecraft.server.level.PlayerChunkMap$EntityTracker.updatePlayers(PlayerChunkMap.java:2258)
[19:24:32 WARN]:        at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:1993)
[19:24:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer.b(ChunkProviderServer.java:1206)
[19:24:32 WARN]:        at net.minecraft.server.level.WorldServer$a.e(WorldServer.java:2548)
[19:24:32 WARN]:        at net.minecraft.server.level.WorldServer$a.b(WorldServer.java:2493)
[19:24:32 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.e(PersistentEntitySectionManager.java:227)
[19:24:32 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.a(PersistentEntitySectionManager.java:187)
[19:24:32 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$processPendingLoads$13(PersistentEntitySectionManager.java:379)
[19:24:32 WARN]:        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[19:24:32 WARN]:        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[19:24:32 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.g(PersistentEntitySectionManager.java:378)
[19:24:32 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.a(PersistentEntitySectionManager.java:392)
[19:24:32 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:720)
[19:24:32 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619)
[19:24:32 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[19:24:32 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1482)
[19:24:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[19:24:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[19:24:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by diogotcorreia** [comment]
This has already been fixed in the latest commits, an update will come out later tonight.
