### ISSUE TITLE
Error when connecting player to server

### ISSUE THREAD

**Issue by fadfhkdfga** [tritonmc/Triton#271]
### Describe the bug

[04:40:54] [Server thread/ERROR]: [Triton] Unhandled exception occurred in onPacketSending(PacketEvent) for Triton
java.lang.RuntimeException: Could not get TileEntityType registry. Incompatible Minecraft version.
	at com.rexcantor64.triton.utils.RegistryUtils.lambda$calculateTileEntityTypeRegistry$1(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.rexcantor64.triton.utils.RegistryUtils.calculateTileEntityTypeRegistry(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.utils.RegistryUtils.getTileEntityTypeKey(RegistryUtils.java:17) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.protocollib.SignPacketHandler.handleLevelChunk(SignPacketHandler.java:82) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.onPacketSending(ProtocolLibListener.java:686) ~[Triton-v3.8.2.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib-608.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.trackChunk(ServerPlayer.java:2246) ~[?:?]
	at net.minecraft.server.level.ChunkMap.playerLoadedChunk(ChunkMap.java:1413) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ChunkMap.updateChunkTracking(ChunkMap.java:840) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader$PlayerLoaderData.sendChunk(PlayerChunkLoader.java:875) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:584) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:741) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1004) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-361]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:40:54] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket@67ad64fa[
    a=8
    b=-5
    c=net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData@301b0f82
    d=net.minecraft.network.protocol.game.ClientboundLightUpdatePacketData@50ce2e93
    ready=true
  ]
[04:40:54] [Server thread/ERROR]: [Triton] Unhandled exception occurred in onPacketSending(PacketEvent) for Triton
java.lang.RuntimeException: Could not get TileEntityType registry. Incompatible Minecraft version.
	at com.rexcantor64.triton.utils.RegistryUtils.lambda$calculateTileEntityTypeRegistry$1(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.rexcantor64.triton.utils.RegistryUtils.calculateTileEntityTypeRegistry(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.utils.RegistryUtils.getTileEntityTypeKey(RegistryUtils.java:17) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.protocollib.SignPacketHandler.handleLevelChunk(SignPacketHandler.java:82) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.onPacketSending(ProtocolLibListener.java:686) ~[Triton-v3.8.2.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib-608.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.trackChunk(ServerPlayer.java:2246) ~[?:?]
	at net.minecraft.server.level.ChunkMap.playerLoadedChunk(ChunkMap.java:1413) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ChunkMap.updateChunkTracking(ChunkMap.java:840) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader$PlayerLoaderData.sendChunk(PlayerChunkLoader.java:875) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:584) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:741) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1004) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-361]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:40:54] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket@7083b5d4[
    a=7
    b=-5
    c=net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData@48eafd47
    d=net.minecraft.network.protocol.game.ClientboundLightUpdatePacketData@16184373
    ready=true
  ]

[04:40:55] [Server thread/ERROR]: [Triton] Unhandled exception occurred in onPacketSending(PacketEvent) for Triton
java.lang.RuntimeException: Could not get TileEntityType registry. Incompatible Minecraft version.
	at com.rexcantor64.triton.utils.RegistryUtils.lambda$calculateTileEntityTypeRegistry$1(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.rexcantor64.triton.utils.RegistryUtils.calculateTileEntityTypeRegistry(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.utils.RegistryUtils.getTileEntityTypeKey(RegistryUtils.java:17) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.protocollib.SignPacketHandler.handleLevelChunk(SignPacketHandler.java:82) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.onPacketSending(ProtocolLibListener.java:686) ~[Triton-v3.8.2.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib-608.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.trackChunk(ServerPlayer.java:2246) ~[?:?]
	at net.minecraft.server.level.ChunkMap.playerLoadedChunk(ChunkMap.java:1413) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ChunkMap.updateChunkTracking(ChunkMap.java:840) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader$PlayerLoaderData.sendChunk(PlayerChunkLoader.java:875) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:584) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:741) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1004) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-361]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:40:55] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket@3304a6d1[
    a=7
    b=-6
    c=net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData@335c4f3a
    d=net.minecraft.network.protocol.game.ClientboundLightUpdatePacketData@235a793a
    ready=true
  ]

[04:40:55] [Server thread/ERROR]: [Triton] Unhandled exception occurred in onPacketSending(PacketEvent) for Triton
java.lang.RuntimeException: Could not get TileEntityType registry. Incompatible Minecraft version.
	at com.rexcantor64.triton.utils.RegistryUtils.lambda$calculateTileEntityTypeRegistry$1(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.rexcantor64.triton.utils.RegistryUtils.calculateTileEntityTypeRegistry(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.utils.RegistryUtils.getTileEntityTypeKey(RegistryUtils.java:17) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.protocollib.SignPacketHandler.handleLevelChunk(SignPacketHandler.java:82) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.onPacketSending(ProtocolLibListener.java:686) ~[Triton-v3.8.2.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib-608.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.trackChunk(ServerPlayer.java:2246) ~[?:?]
	at net.minecraft.server.level.ChunkMap.playerLoadedChunk(ChunkMap.java:1413) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ChunkMap.updateChunkTracking(ChunkMap.java:840) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader$PlayerLoaderData.sendChunk(PlayerChunkLoader.java:875) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:584) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:741) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1004) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-361]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:40:55] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket@5ba5a72b[
    a=7
    b=-2
    c=net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData@3c6ac37e
    d=net.minecraft.network.protocol.game.ClientboundLightUpdatePacketData@3f3296b6
    ready=true
  ]

[04:40:55] [Server thread/ERROR]: [Triton] Unhandled exception occurred in onPacketSending(PacketEvent) for Triton
java.lang.RuntimeException: Could not get TileEntityType registry. Incompatible Minecraft version.
	at com.rexcantor64.triton.utils.RegistryUtils.lambda$calculateTileEntityTypeRegistry$1(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.rexcantor64.triton.utils.RegistryUtils.calculateTileEntityTypeRegistry(RegistryUtils.java:50) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.utils.RegistryUtils.getTileEntityTypeKey(RegistryUtils.java:17) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.protocollib.SignPacketHandler.handleLevelChunk(SignPacketHandler.java:82) ~[Triton-v3.8.2.jar:?]
	at com.rexcantor64.triton.packetinterceptor.ProtocolLibListener.onPacketSending(ProtocolLibListener.java:686) ~[Triton-v3.8.2.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib-608.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib-608.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.trackChunk(ServerPlayer.java:2246) ~[?:?]
	at net.minecraft.server.level.ChunkMap.playerLoadedChunk(ChunkMap.java:1413) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ChunkMap.updateChunkTracking(ChunkMap.java:840) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader$PlayerLoaderData.sendChunk(PlayerChunkLoader.java:875) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:584) ~[paper-1.19.3.jar:git-Paper-361]
	at io.papermc.paper.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:741) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1004) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:2725) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.executeMidTickTasks(MinecraftServer.java:2748) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:919) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-361]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-361]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:40:55] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket@1a08d973[
    a=6
    b=-1
    c=net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData@1ded11d9
    d=net.minecraft.network.protocol.game.ClientboundLightUpdatePacketData@3dd8437e
    ready=true
  ]

### How can the bug be reproduced?

The above error log is continuously output.

### Which Spigot fork are you using?

PaperMC

### What's your server version?

git-Paper-361 (MC: 1.19.3)

### Which proxy are you using?

BungeeCord

### What's your proxy version?

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:a5b6eb6:1674

### What's the MC version of your client?

1.19.3

### What's the Triton version you're using?

3.8.2

**Comment by diogotcorreia** [comment]
Hi!
Have you tried the 1.19.3 development build I've posted in the #support channel on Discord? It's pinned.

I haven't published it to SpigotMC yet because there's a small bug that I haven't finished yet.
