### ISSUE TITLE
Error when injecting protocol on Bungee if connection is canceled

### ISSUE THREAD

**Issue by diogotcorreia** [tritonmc/Triton#289]
### Describe the bug

If the client connection is cancelled (e.g. maintenance) the package injector fails.

### Which Spigot fork are you using?

Vanilla Spigot (from BuildTools)

### What's your server version?

irrelevant

### Which proxy are you using?

BungeeCord

### What's your proxy version?

irrelevant

### What's the MC version of your client?

irrelevant

### What's the Triton version you're using?

irrelevant

### Additional Information

```
[13:41:36 ERROR] [Triton]: [PacketInjector] Failed to inject client connection for f6c4f5ae-267c-4a53-9e6c-ae00583fd325
[13:41:36 ERROR]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "<parameter1>" is null
[13:41:36 ERROR]:       at com.rexcantor64.triton.utils.NMSUtils.getDeclaredField(NMSUtils.java:64)
[13:41:36 ERROR]:       at com.rexcantor64.triton.utils.NMSUtils.getDeclaredField(NMSUtils.java:60)
[13:41:36 ERROR]:       at com.rexcantor64.triton.BungeeMLP.injectPipeline(BungeeMLP.java:124)
[13:41:36 ERROR]:       at com.rexcantor64.triton.listeners.BungeeListener.lambda$onLogin$0(BungeeListener.java:49)
[13:41:36 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[13:41:36 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:41:36 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:41:36 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by diogotcorreia** [comment]
I was not able to reproduce the issue, but I'll handle this gracefully from now on.
