### ISSUE TITLE
Cannot start Triton v4 on MC 1.20.2

### ISSUE THREAD

**Issue by Esmaay** [tritonmc/Triton#327]
### Describe the bug

When running the plugin on 1.20.2, the plugin will disable on startup.

The error:
`[12:47:37] [Server thread/INFO]: [Triton] Loaded MySQL storage manager
[12:47:37] [Server thread/INFO]: [Triton] Successfully setup the Language Manager! 3 languages loaded!
[12:47:37] [Server thread/INFO]: [Triton] Successfully setup the Translation Manager! 0 text translations and 0 sign translations loaded!
[12:47:37] [Server thread/ERROR]: Error occurred while enabling Triton v4.0.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: Unable to find a field "null" with the type class net.minecraft.advancements.AdvancementDisplay in class net.minecraft.advancements.Advancement$SerializedAdvancement
    at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:392) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:55) ~[ProtocolLib.jar:?]
    at com.rexcantor64.triton.spigot.packetinterceptor.AdvancementsPacketHandler.<init>(AdvancementsPacketHandler.java:35) ~[Triton-4.0.0-SNAPSHOT-all.jar:?]
    at com.rexcantor64.triton.spigot.packetinterceptor.ProtocolLibListener.<init>(ProtocolLibListener.java:119) ~[Triton-4.0.0-SNAPSHOT-all.jar:?]
    at com.rexcantor64.triton.spigot.SpigotTriton.onEnable(SpigotTriton.java:112) ~[Triton-4.0.0-SNAPSHOT-all.jar:?]
    at com.rexcantor64.triton.spigot.plugin.SpigotPlugin.onEnable(SpigotPlugin.java:20) ~[Triton-4.0.0-SNAPSHOT-all.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2076]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2076]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:658) ~[purpur-1.20.2.jar:git-Purpur-2076]
    at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:569) ~[purpur-1.20.2.jar:git-Purpur-2076]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:630) ~[purpur-1.20.2.jar:git-Purpur-2076]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.20.2.jar:git-Purpur-2076]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.20.2.jar:git-Purpur-2076]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[purpur-1.20.2.jar:git-Purpur-2076]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[purpur-1.20.2.jar:git-Purpur-2076]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:47:37] [Server thread/INFO]: [Triton] Disabling Triton v4.0.0-SNAPSHOT`

### How can the bug be reproduced?

1. Install Triton on 1.20.2 server
2. Start the server
3. Triton will crash.

### Expected behaviour

The plugin should enable like usual.

### Which Spigot fork are you using?

Purpur

### What's your server version?

git-purpur-2076 (MC: 1.20.2)

### Which proxy are you using?

Velocity

### What's your proxy version?

3.2.0-SNAPSHOT (git-1b076599)

### What's the MC version of your client?

1.20.2

### What's the Triton version you're using?

4.0.0-SNAPSHOT

**Comment by assada** [comment]
Any ETA?

**Comment by diogotcorreia** [comment]
@assada hopefully tomorrow
